using secret values from 1password for local development workflow

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -9,42 +9,49 @@ set -eu -o pipefail
 
 # check node exists
 if ! which node > /dev/null ; then
-	echo "node not found on the system. Install version in .nvmrc based on instructions in README"
-	exit 1
+    echo "node not found on the system. Install version in .nvmrc based on instructions in README"
+    exit 1
 fi
 
 # check node version
 if ! diff .nvmrc <(node -v) > /dev/null ; then
-	echo "Uh Oh! The current node version does not match the version required in .nvmrc"
-	echo "If you have installed nvm, simply running 'nvm use' in this directory should solve the problem"
-	echo "If you don't have nvm yet, the instructions in the README should sort you."
-	echo "** Don't forget to add the bit to your shell profile **"
-	exit 1
+    echo "Uh Oh! The current node version does not match the version required in .nvmrc"
+    echo "If you have installed nvm, simply running 'nvm use' in this directory should solve the problem"
+    echo "If you don't have nvm yet, the instructions in the README should sort you."
+    echo "** Don't forget to add the bit to your shell profile **"
+    exit 1
 fi
 
 # check yarn exists
 if ! which yarn > /dev/null ; then
-	echo "yarn not found on the system. On macOS, you can install it with 'brew install yarn'"
-	exit 1
+    echo "yarn not found on the system. On macOS, you can install it with 'brew install yarn'"
+    exit 1
 fi
 
 # check serverless is installed globally.
 if ! which serverless > /dev/null ; then
-	echo "installing serverless globally"
-	yarn install -g serverless
+    echo "installing serverless globally"
+    yarn install -g serverless
+fi
+
+# check if 1password cli is installed
+if ! which op > /dev/null ; then
+    echo "The MDCT team uses 1Password to store and retrive development credentials. If you do not have a 1Password account please request one."
+    exit 1
 fi
 
 # have to ensure that yarn install is up to date.
 # we use .yarn_install as a marker for the last time `yarn install` was run. Rerun the command when yarn.lock is updated
 if [ "yarn.lock" -nt ".yarn_install" ]; then
-	yarn install
-	touch .yarn_install
+    yarn install
+    touch .yarn_install
 fi
 
-# if .env doesn't exist, copy .env_example there
-if [ ! -f .env ]; then 
-	cp .env_example .env
-fi
+#inject secrets to .env
+op inject -i .env.tpl -o .env -f
+
+#inject secrets to .env
+op inject -i services/ui-src/.env.tpl -o services/ui-src/.env -f
 
 # build and run dev.ts
 # tsc is configured to build what we expect in tsconfig.json
