Use different exit codes

diff --git a/.github/workflows/create-pr.yml b/.github/workflows/create-pr.yml
--- a/.github/workflows/create-pr.yml
+++ b/.github/workflows/create-pr.yml
@@ -36,12 +36,23 @@ jobs:
       - name: Generate PR body
         id: pr_body
         run: |
-          body=$(
-            .github/commit-log.sh "$HEAD_BRANCH" "$BASE_BRANCH"
-          ) || exit_code=$?
+          body=$(.github/commit-log.sh "$HEAD_BRANCH" "$BASE_BRANCH")
+          exit_code=$?
 
           if [ "$exit_code" == "1" ]; then
-            echo "No commits. Skipping PR."
+            echo "No commits between $HEAD_BRANCH and $BASE_BRANCH. Skipping PR creation."
+            echo "skip=true" >> $GITHUB_OUTPUT
+            exit 0
+          fi
+
+          if [ "$exit_code" == "2" ]; then
+            echo "$HEAD_BRANCH branch not found. Skipping PR creation."
+            echo "skip=true" >> $GITHUB_OUTPUT
+            exit 0
+          fi
+
+          if [ "$exit_code" == "3" ]; then
+            echo "$BASE_BRANCH branch not found. Skipping PR creation."
             echo "skip=true" >> $GITHUB_OUTPUT
             exit 0
           fi
