CMDCT-4364 - cdk conversion (DONT MERGE YET!) (#12293)
Co-authored-by: Pete Dunlap <pete.dunlap@stratiform.digital>

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -11,9 +11,6 @@ permissions:
   pages: write
   actions: read
 
-env:
-  SERVERLESS_LICENSE_KEY: ${{ secrets.SERVERLESS_LICENSE_KEY }}
-
 jobs:
   unit-tests:
     name: Unit Tests
@@ -59,8 +56,6 @@ jobs:
     if: ${{ !startsWith(github.ref_name, 'skipci') && !startsWith(github.ref_name, 'code-json-') }}
     needs: unit-tests
     runs-on: ubuntu-latest
-    env:
-      SLS_DEPRECATION_DISABLE: "*" # Turn off deprecation warnings in the pipeline
     steps:
       - uses: actions/checkout@v4
       - name: set branch_name # Some integrations (Dependabot & Snyk) build very long branch names. This is a switch to make long branch names shorter.
@@ -101,7 +96,7 @@ jobs:
           ./run deploy --stage $branch_name
       - id: endpoint
         run: |
-          APPLICATION_ENDPOINT=$(./output.sh ui ApplicationEndpointUrl $branch_name)
+          APPLICATION_ENDPOINT=$(../scripts/output.sh mcr-$branch_name CloudFrontUrl)
           echo "application_endpoint=$APPLICATION_ENDPOINT" >> $GITHUB_OUTPUT
           echo "## Application Endpoint" >> $GITHUB_STEP_SUMMARY
           echo "<$APPLICATION_ENDPOINT>" >> $GITHUB_STEP_SUMMARY
@@ -111,99 +106,99 @@ jobs:
       BRANCH_SPECIFIC_VARNAME_AWS_DEFAULT_REGION: ${{ steps.set_names.outputs.BRANCH_SPECIFIC_VARNAME_AWS_DEFAULT_REGION }}
       BRANCH_SPECIFIC_VARNAME_AWS_OIDC_ROLE_TO_ASSUME: ${{ steps.set_names.outputs.BRANCH_SPECIFIC_VARNAME_AWS_OIDC_ROLE_TO_ASSUME }}
 
-  register-runner:
-    name: Register GitHub Runner
-    if: ${{ github.ref_name != 'main' && github.ref_name != 'val' && github.ref_name != 'production' && !startsWith(github.ref_name, 'skipci') && !startsWith(github.ref_name, 'code-json-') }}
-    runs-on: ubuntu-latest
-    needs: deploy
-    env:
-      SLS_DEPRECATION_DISABLE: "*" # Turn off deprecation warnings in the pipeline
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+  # register-runner:
+  #   name: Register GitHub Runner
+  #   if: ${{ github.ref_name != 'main' && github.ref_name != 'val' && github.ref_name != 'production' }}
+  #   runs-on: ubuntu-latest
+  #   needs: deploy
+  #   env:
+  #     SLS_DEPRECATION_DISABLE: "*" # Turn off deprecation warnings in the pipeline
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      - name: set branch_name
-        run: |
-          BRANCH_NAME=$(./.github/setBranchName.sh ${{ github.ref_name }})
-          echo "branch_name=${BRANCH_NAME}" >> $GITHUB_ENV
+  #     - name: set branch_name
+  #       run: |
+  #         BRANCH_NAME=$(./.github/setBranchName.sh ${{ github.ref_name }})
+  #         echo "branch_name=${BRANCH_NAME}" >> $GITHUB_ENV
 
-      - name: set branch specific variable names
-        id: set_names
-        run: ./.github/build-vars.sh set_names
+  #     - name: set branch specific variable names
+  #       id: set_names
+  #       run: ./.github/build-vars.sh set_names
 
-      - name: set variable values
-        id: set_values
-        run: ./.github/build-vars.sh set_values
-        env:
-          AWS_DEFAULT_REGION: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_AWS_DEFAULT_REGION] || secrets.AWS_DEFAULT_REGION }}
-          AWS_OIDC_ROLE_TO_ASSUME: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_AWS_OIDC_ROLE_TO_ASSUME] || secrets.AWS_OIDC_ROLE_TO_ASSUME }}
+  #     - name: set variable values
+  #       id: set_values
+  #       run: ./.github/build-vars.sh set_values
+  #       env:
+  #         AWS_DEFAULT_REGION: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_AWS_DEFAULT_REGION] || secrets.AWS_DEFAULT_REGION }}
+  #         AWS_OIDC_ROLE_TO_ASSUME: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_AWS_OIDC_ROLE_TO_ASSUME] || secrets.AWS_OIDC_ROLE_TO_ASSUME }}
 
-      - name: Configure AWS credentials for GitHub Actions
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_AWS_OIDC_ROLE_TO_ASSUME] || secrets.AWS_OIDC_ROLE_TO_ASSUME }}
-          aws-region: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_AWS_DEFAULT_REGION] || secrets.AWS_DEFAULT_REGION }}
+  #     - name: Configure AWS credentials for GitHub Actions
+  #       uses: aws-actions/configure-aws-credentials@v4
+  #       with:
+  #         role-to-assume: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_AWS_OIDC_ROLE_TO_ASSUME] || secrets.AWS_OIDC_ROLE_TO_ASSUME }}
+  #         aws-region: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_AWS_DEFAULT_REGION] || secrets.AWS_DEFAULT_REGION }}
 
-      - name: output account id
-        id: output_account_id
-        run: |
-          #!/bin/bash
-          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
-          echo "Current Account ID: ${AWS_ACCOUNT_ID}"
+  #     - name: output account id
+  #       id: output_account_id
+  #       run: |
+  #         #!/bin/bash
+  #         AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
+  #         echo "Current Account ID: ${AWS_ACCOUNT_ID}"
 
-      - name: Get Github Actions CIDR Blocks
-        id: get-gha-cidrs
-        shell: bash
-        run: |
-          #!/bin/bash
-          GHA_RESP=$(curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/meta)
-          echo "Response for GHA runner CIDR blocks:  $GHA_RESP"
-          IPV4_CIDR_ARR=($(echo $GHA_RESP | jq -r '.actions | .[]' | grep -v ':'))
-          GHA_CIDRS_IPV4=$(echo $(IFS=" "; echo ${IPV4_CIDR_ARR[*]}))
-          echo "GHA_CIDRS_IPV4=$GHA_CIDRS_IPV4" >> $GITHUB_OUTPUT
+  #     - name: Get Github Actions CIDR Blocks
+  #       id: get-gha-cidrs
+  #       shell: bash
+  #       run: |
+  #         #!/bin/bash
+  #         GHA_RESP=$(curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/meta)
+  #         echo "Response for GHA runner CIDR blocks:  $GHA_RESP"
+  #         IPV4_CIDR_ARR=($(echo $GHA_RESP | jq -r '.actions | .[]' | grep -v ':'))
+  #         GHA_CIDRS_IPV4=$(echo $(IFS=" "; echo ${IPV4_CIDR_ARR[*]}))
+  #         echo "GHA_CIDRS_IPV4=$GHA_CIDRS_IPV4" >> $GITHUB_OUTPUT
 
-      - name: Generate IP Set Name
-        id: gen-ip-set-name
-        run: |
-          #!/bin/bash
-          STAGE_GH_IPSET_NAME=$branch_name-gh-ipset
-          echo "Github IP Set name:  $STAGE_GH_IPSET_NAME"
-          echo "STAGE_GH_IPSET_NAME=$STAGE_GH_IPSET_NAME" >> $GITHUB_OUTPUT
+  #     - name: Generate IP Set Name
+  #       id: gen-ip-set-name
+  #       run: |
+  #         #!/bin/bash
+  #         STAGE_GH_IPSET_NAME=$branch_name-gh-ipset
+  #         echo "Github IP Set name:  $STAGE_GH_IPSET_NAME"
+  #         echo "STAGE_GH_IPSET_NAME=$STAGE_GH_IPSET_NAME" >> $GITHUB_OUTPUT
 
-      - name: Fetch AWS IP Set Metadata
-        id: fetch-ip-set-info
-        run: |
-          #!/bin/bash
-          # Fetch AWS IP set ARNs using AWS CLI and store them in a variable
-          AWS_IP_SET_INFO=$(aws wafv2 list-ip-sets --scope=CLOUDFRONT)
-          echo "Outputting AWS IP Set Info:  ${AWS_IP_SET_INFO}"
-          # Store the IP set ARNs in an output variable using GITHUB_OUTPUT
-          IPSET_NAME=${{ steps.gen-ip-set-name.outputs.STAGE_GH_IPSET_NAME }}
-          IPSET=$(jq '.IPSets | map(select(.Name == "'${IPSET_NAME}'")) | .[]' <<< ${AWS_IP_SET_INFO})
-          [ -z "$IPSET" ] && echo "IP Set with name ${IPSET_NAME} was not located.  Exiting..." && exit 1
-          echo "IP Set metadata:  ${IPSET}"
-          #Get Values from the IP SET
-          IPSET_ID=$(jq -r '.Id' <<< ${IPSET})
-          echo "IPSET_ARN=$IPSET_ARN" >> $GITHUB_OUTPUT
-          echo "IPSET_NAME=$IPSET_NAME" >> $GITHUB_OUTPUT
-          echo "IPSET_ID=$IPSET_ID" >> $GITHUB_OUTPUT
+  #     - name: Fetch AWS IP Set Metadata
+  #       id: fetch-ip-set-info
+  #       run: |
+  #         #!/bin/bash
+  #         # Fetch AWS IP set ARNs using AWS CLI and store them in a variable
+  #         AWS_IP_SET_INFO=$(aws wafv2 list-ip-sets --scope=CLOUDFRONT)
+  #         echo "Outputting AWS IP Set Info:  ${AWS_IP_SET_INFO}"
+  #         # Store the IP set ARNs in an output variable using GITHUB_OUTPUT
+  #         IPSET_NAME=${{ steps.gen-ip-set-name.outputs.STAGE_GH_IPSET_NAME }}
+  #         IPSET=$(jq '.IPSets | map(select(.Name == "'${IPSET_NAME}'")) | .[]' <<< ${AWS_IP_SET_INFO})
+  #         [ -z "$IPSET" ] && echo "IP Set with name ${IPSET_NAME} was not located.  Exiting..." && exit 1
+  #         echo "IP Set metadata:  ${IPSET}"
+  #         #Get Values from the IP SET
+  #         IPSET_ID=$(jq -r '.Id' <<< ${IPSET})
+  #         echo "IPSET_ARN=$IPSET_ARN" >> $GITHUB_OUTPUT
+  #         echo "IPSET_NAME=$IPSET_NAME" >> $GITHUB_OUTPUT
+  #         echo "IPSET_ID=$IPSET_ID" >> $GITHUB_OUTPUT
 
-      - name: Update IP Set
-        id: update-ip-set
-        run: ./.github/waf-controller.sh set ${{ steps.fetch-ip-set-info.outputs.IPSET_NAME }} ${{ steps.fetch-ip-set-info.outputs.IPSET_ID }} ${{ steps.get-gha-cidrs.outputs.GHA_CIDRS_IPV4 }}
-        env:
-          AWS_RETRY_MODE: adaptive
-          AWS_MAX_ATTEMPTS: 10
+  #     - name: Update IP Set
+  #       id: update-ip-set
+  #       run: ./.github/waf-controller.sh set ${{ steps.fetch-ip-set-info.outputs.IPSET_NAME }} ${{ steps.fetch-ip-set-info.outputs.IPSET_ID }} ${{ steps.get-gha-cidrs.outputs.GHA_CIDRS_IPV4 }}
+  #       env:
+  #         AWS_RETRY_MODE: adaptive
+  #         AWS_MAX_ATTEMPTS: 10
 
-    outputs:
-      ipset_name: ${{ steps.fetch-ip-set-info.outputs.IPSET_NAME }}
-      ipset_id: ${{ steps.fetch-ip-set-info.outputs.IPSET_ID }}
+  #   outputs:
+  #     ipset_name: ${{ steps.fetch-ip-set-info.outputs.IPSET_NAME }}
+  #     ipset_id: ${{ steps.fetch-ip-set-info.outputs.IPSET_ID }}
 
   e2e-test:
     name: E2E Integration Tests
     needs:
       - deploy
-      - register-runner
+      # - register-runner
     if: ${{ always() && !cancelled() && needs.deploy.result == 'success' && github.ref_name != 'production' && !startsWith(github.ref_name, 'skipci') && !startsWith(github.ref_name, 'code-json-') }}
     runs-on: ubuntu-latest
     steps:
@@ -242,7 +237,7 @@ jobs:
     name: E2E A11y Tests
     needs:
       - deploy
-      - register-runner
+      # - register-runner
     if: ${{ always() && !cancelled() && needs.deploy.result == 'success' && github.ref_name != 'production' && !startsWith(github.ref_name, 'skipci') && !startsWith(github.ref_name, 'code-json-') }}
     runs-on: ubuntu-latest
     steps:
@@ -278,9 +273,9 @@ jobs:
     name: Playwright Tests
     needs:
       - deploy
-      - register-runner
-      - e2e-test
-      - a11y-tests
+      # - register-runner
+      # - e2e-test
+      # - a11y-tests
     if: ${{ always() && !cancelled() && needs.deploy.result == 'success' && github.ref_name != 'production' && !startsWith(github.ref_name, 'skipci') && !startsWith(github.ref_name, 'code-json-') }}
     timeout-minutes: 60
     runs-on: ubuntu-latest
@@ -369,33 +364,33 @@ jobs:
           echo "## Playwright Test Results" >> $GITHUB_STEP_SUMMARY
           echo "https://${ORG_NAME}.github.io/${REPO_NAME}/${{ steps.timestampid.outputs.timestamp }}/" >> $GITHUB_STEP_SUMMARY
 
-  cleanup:
-    name: Delist GHA Runner CIDR Blocks
-    if: ${{ github.ref_name != 'main' && github.ref_name != 'val' && github.ref_name != 'production' && !startsWith(github.ref_name, 'skipci') && !startsWith(github.ref_name, 'code-json-') }}
-    runs-on: ubuntu-latest
-    needs:
-      - register-runner
-      - a11y-tests
-      - e2e-test
-      - test
-    env:
-      SLS_DEPRECATION_DISABLE: "*" # Turn off deprecation warnings in the pipeline
-    steps:
-      - uses: actions/checkout@v4
-      - name: Configure AWS credentials for GitHub Actions
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_AWS_OIDC_ROLE_TO_ASSUME] || secrets.AWS_OIDC_ROLE_TO_ASSUME }}
-          aws-region: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_AWS_DEFAULT_REGION] || secrets.AWS_DEFAULT_REGION }}
-      - name: output account id
-        id: output_account_id
-        run: |
-          #!/bin/bash
-          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
-          echo "Current Account ID: ${AWS_ACCOUNT_ID}"
-      - name: cleanup-ip-list
-        id: reset-ip-set
-        run: ./.github/waf-controller.sh set ${{ needs.register-runner.outputs.ipset_name }} ${{ needs.register-runner.outputs.ipset_id }} '[]'
-        env:
-          AWS_RETRY_MODE: adaptive
-          AWS_MAX_ATTEMPTS: 10
+  # cleanup:
+  #   name: Delist GHA Runner CIDR Blocks
+  #   if: ${{ github.ref_name != 'main' && github.ref_name != 'val' && github.ref_name != 'production' }}
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     # - register-runner
+  #     - a11y-tests
+  #     - e2e-test
+  #     - test
+  #   env:
+  #     SLS_DEPRECATION_DISABLE: "*" # Turn off deprecation warnings in the pipeline
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - name: Configure AWS credentials for GitHub Actions
+  #       uses: aws-actions/configure-aws-credentials@v4
+  #       with:
+  #         role-to-assume: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_AWS_OIDC_ROLE_TO_ASSUME] || secrets.AWS_OIDC_ROLE_TO_ASSUME }}
+  #         aws-region: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_AWS_DEFAULT_REGION] || secrets.AWS_DEFAULT_REGION }}
+  #     - name: output account id
+  #       id: output_account_id
+  #       run: |
+  #         #!/bin/bash
+  #         AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
+  #         echo "Current Account ID: ${AWS_ACCOUNT_ID}"
+  #     - name: cleanup-ip-list
+  #       id: reset-ip-set
+  #       run: ./.github/waf-controller.sh set ${{ needs.register-runner.outputs.ipset_name }} ${{ needs.register-runner.outputs.ipset_id }} '[]'
+  #       env:
+  #         AWS_RETRY_MODE: adaptive
+  #         AWS_MAX_ATTEMPTS: 10
