SnykTest

diff --git a/.github/workflows/snyk-test.yml b/.github/workflows/snyk-test.yml
--- a/.github/workflows/snyk-test.yml
+++ b/.github/workflows/snyk-test.yml
@@ -41,11 +41,22 @@ jobs:
       run: npm install -g snyk
       working-directory: ./
 
-    - name: Run Snyk Test
-      run: npx snyk test --all-projects --json > snyk_output.txt 
+    - name: Run Snyk test
+      run: |
+            snyk test --all-projects --json > snyk_output.txt || {
+            echo "Snyk test failed. Last 10 lines of the output:"
+            tail -n 10 snyk_output.txt
+            exit 1
+          }
       working-directory: ./
       env:
-        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} # check 
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+
+    # - name: Run Snyk Test
+    #   run:  snyk test --all-projects --json > snyk_output.txt 
+    #   working-directory: ./
+    #   env:
+    #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} # check 
 
     - name: Set environment variables
       run: |
@@ -79,7 +90,7 @@ jobs:
         working-directory: ./
 
       - name: Run Snyk test
-        run: npx snyk test --all-projects --json > snyk_output.txt
+        run:  snyk test --all-projects --json > snyk_output.txt
         working-directory: ./
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
