SnykTest

diff --git a/.github/workflows/snyk-test.yml b/.github/workflows/snyk-test.yml
--- a/.github/workflows/snyk-test.yml
+++ b/.github/workflows/snyk-test.yml
@@ -78,22 +78,22 @@ jobs:
         run: npm install -g snyk
         working-directory: ./
 
-        #- name: Run Snyk test
-        # run: npx snyk test --all-projects --json > snyk_output.txt || true
-        # working-directory: ./
-        # env:
-        #   SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-
       - name: Run Snyk test
-        run: |
-          npx snyk test --all-projects --json > snyk_output.txt || {
-            echo "Snyk test failed. Last 10 lines of the output:"
-            tail -n 10 snyk_output.txt
-            exit 1
-          }
+        run: npx snyk test --all-projects --json > snyk_output.txt || true
         working-directory: ./
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+
+      # - name: Run Snyk test
+      #   run: |
+      #     npx snyk test --all-projects --json > snyk_output.txt || {
+      #       echo "Snyk test failed. Last 10 lines of the output:"
+      #       tail -n 10 snyk_output.txt
+      #       exit 1
+      #     }
+      #   working-directory: ./
+      #   env:
+      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
       - name: Set environment variables
         run: |
